evarist/controllers/workflow.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from bson.objectid import ObjectId
import os, time, datetime, urllib, urllib2, random
from flask import current_app, Flask, Blueprint, request, session, g, redirect, url_for, \
    abort, render_template, flash
from contextlib import closing
from flask_mail import Message
from functools import wraps
from evarist.models import (solution_filters, events,
                            parameters)
from evarist.forms import (WebsiteFeedbackForm, CommentForm, 
                            SolutionForm, FeedbackToSolutionForm, 
                            EditSolutionForm, VoteForm, 
                            trigger_flash_error)
from evarist.models.mongoengine_models import *
from evarist.controllers.admin import admin_required

from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url
import time, sendgrid

workflow = Blueprint('workflow', __name__,
                        template_folder='templates')


def connect_to_sendgrid(current_app):
    sg = sendgrid.SendGridAPIClient(apikey=current_app.config['SENDGRID_APIKEY'])
    d=time.strftime("%Y-%m-%d")
    params = {'aggregated_by': 'day', 'limit': 1, 'start_date': d, 'end_date': d, 'offset': 1}
    response = sg.client.stats.get(query_params=params)
    # print response

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        
        if not g.user:
            flash('Please, log in first.')
            return redirect(url_for('user.login'))

        return f(*args, **kwargs)
    return decorated_function

@workflow.route('/', methods=["GET", "POST"])
def home():
    # this is example code for sending emails
    # msg = Message("Hello",recipients=["artofkot@gmail.com"])
    # g.mail.send(msg)

    if g.locale == 'ru': matan_course=Course.objects(slug='matan').first()
    else: matan_course=Course.objects(slug='analysis').first()

    cosmo_course_home=Course.objects(slug='cosmology').first()
    
    solution_examples_pset=Problem_set.objects(slug='solution_examples').first()

    return render_template('home.html',
                        cosmo_course=cosmo_course_home,
                        matan_course=matan_course,
                        solution_examples_pset=solution_examples_pset)


@workflow.route('/users', methods=["GET", "POST"])    
def users():

    users=User.objects().order_by('-karma')

    users=users[:10]

    return render_template('users.html',
                            users=users)


@workflow.route('/home')
def index():
    return redirect(url_for('.home'))

@workflow.route('/about')
def about():
    upvote_correctness_threshold=parameters.upvote_correctness_threshold
    return render_template('about.html',
        upvote_correctness_threshold=upvote_correctness_threshold)

@workflow.route('/faq')
def faq():
    return render_template('faq.html')

@workflow.route('/blog')
# @admin_required
def blog():
    return render_template('blog.html')


@workflow.route('/contact', methods=["GET", "POST"])
def contact():
    website_feedback_form=WebsiteFeedbackForm()
    if website_feedback_form.validate_on_submit():
        feedback=CommentFeedback(text=website_feedback_form.feedback.data,
                                type_='feedback',
                                where_feedback='homepage')
        if g.user: 
            feedback.author=g.user
            feedback.author_email=g.user.email
        else: feedback.author_email=website_feedback_form.email.data
        
        feedback.save()

        g.mail.send(Message(body=feedback.text,
                            sender=feedback.author_email,
                            subject='feedback',
                            recipients=current_app.config['ADMINS']))


        flash('Thank you for your feedback!')
        return redirect(url_for('workflow.contact'))

        

    return render_template('contact.html',
        website_feedback_form=website_feedback_form)

@workflow.route('/course/<course_slug>/', methods=["GET", "POST"])
def course(course_slug):
    # get the problem set
    
    course=Course.objects(slug=course_slug).first()
    if not course: 
        flash('No such course.')
        return redirect(url_for('.home'))


    # is_moderator=False
    # if g.user: is_moderator=g.user['rights']['is_moderator']
    # if (problem_set['status']=='dev') and (not is_moderator):
    #     flash('This problem set is not ready yet.')
    #     return redirect(url_for('.home'))

    
    return render_template('course.html', 
                            course=course)

@workflow.route('/course/cosmology/', methods=["GET", "POST"])
def cosmology():
    # get the problem set
    
    cosmo_course=Course.objects(slug='cosmology').first()
    if not cosmo_course: 
        flash('No such course.')
        return redirect(url_for('.home'))
    
    return render_template('cosmology.html',
                            cosmo_course=cosmo_course)

@workflow.route('/problem_sets/<problem_set_slug>/', methods=["GET", "POST"])
def problem_set(problem_set_slug):
    # get the problem set
    
    problem_set=Problem_set.objects(slug=problem_set_slug).first()
    if not problem_set: 
        flash('No such problem set.')
        return redirect(url_for('.home'))

    if "eng" in problem_set.tags: 
        engtag="eng"
    else: engtag="ru"

    is_moderator=False
    if g.user: is_moderator=g.user['rights']['is_moderator']
    if (problem_set['status']=='dev') and (not is_moderator):
        flash('This problem set is not ready yet.')
        return redirect(url_for('.home'))

    
    return render_template('problem_set.html', 
                            problem_set=problem_set,
                            engtag=engtag)

@workflow.route('/problem_sets/<problem_set_slug>/<type_>/<__id>/', methods=["GET", "POST"])
def content_block(problem_set_slug,type_,__id):

    content_block=Content_block.objects(id=ObjectId(__id)).first()

    return render_template('content_block.html',
                            content_block=content_block)

@workflow.route('/problem_sets/<problem_set_slug>/problem/<prob_id>/', methods=["GET", "POST"])
def problem(problem_set_slug,prob_id):
    # get the problem_set
    problem_set=Problem_set.objects(slug=problem_set_slug).first()
    if not problem_set: 
        flash('No such problem set.')
        return redirect(url_for('.home'))

    # get the problem
    problem=Content_block.objects(id=ObjectId(prob_id)).first()
    if not problem: 
        flash('No such problem.')
        return redirect(url_for('.home'))

    # check if user can see this problem set
    is_moderator=False
    if g.user: is_moderator=g.user.rights.is_moderator
    if (problem_set['status']=='dev') and (not is_moderator):
        flash('This problem set is not ready yet.')
        return redirect(url_for('.home'))

    # get the current_user_solutions, if its written
    current_user_solutions=[sol for sol in problem.solutions if sol.author==g.user]

    general_comment_form=CommentForm()
    if general_comment_form.validate_on_submit():
        comment=CommentToContent_block(text=general_comment_form.text.data,
                                        author=g.user,
                                        parent_content_block=problem)
        comment.save()
        problem.general_discussion.append(comment)
        problem.save()

        g.mail.send(Message(body= 'http://www.evarist.org/'+url_for('.problem', 
                                problem_set_slug=problem_set_slug,
                                prob_id=problem['id']) + '\r\n\r\n' + problem_set.title + '. Problem ' + str(problem.number_in_problem_set) + '.' + problem.text + '\r\n\r\n'+ 'The question: '+ comment.text,
                            sender=comment.author.email,
                            subject='Вопрос по условию',
                            recipients=current_app.config['ADMINS']))


    vote_form=VoteForm()
    if vote_form.validate_on_submit():
        voted_solution=Solution.objects(id=ObjectId(request.args['sol_id'])).first()
        
        if events.vote(g.user,voted_solution,vote_form.vote.data):
            events.do_events_after_voting(voted_solution)
        else:
            flash('It turns out you already voted for this solution.')

        return redirect(url_for('.problem', 
                                problem_set_slug=problem_set_slug,
                                prob_id=problem['id']))

    solution_comment_form=FeedbackToSolutionForm()
    if solution_comment_form.validate_on_submit():
        parent_solution=Solution.objects(id=ObjectId(request.args['sol_id'])).first()
        comment=CommentToSolution(text=solution_comment_form.feedback_to_solution.data,
            author=g.user,
            parent_solution=parent_solution)
        comment.save()

        events.commented_solution(comment)
            
        return redirect(url_for('.problem', 
                                problem_set_slug=problem_set_slug,
                                prob_id=problem.id))

    solution_form=SolutionForm()
    if solution_form.validate_on_submit():
        file=request.files.get(solution_form.image.name,None)
        image_url=None
        if file:
            upload_result = upload(file)
            image_url=upload_result['url'] 
        solution=Solution(text=solution_form.solution.data,
                        author=g.user,
                        problem=problem,
                        problem_set=problem_set,
                        image_url=image_url)
        solution.save()
        events.solution_written(solution)
        
        if current_app.debug==False and (not problem_set_slug=="sets"):
            g.mail.send(Message(body='http://www.evarist.org/'+url_for('.problem', 
                                problem_set_slug=problem_set_slug,
                                prob_id=problem['id']),
                            subject="Someone posted a solution on evarist",

evarist/templates/blog.html
{% extends "layout.html" %}

{% block head %}
  <title>Evarist - blog.</title>
{% endblock %}

{% block body %}
  <!-- <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <a href="{{url_for('workflow.home')}}">(перейти на главную страницу)</a>
    </div>
  </div> -->
  
  <div style='height:20px'></div>

  <div class="row">

    <div class="col-md-8 col-md-offset-2">
      <!-- First Blog Post -->
      <div id='first_blogpost'>
        <h2>
          Начало!
        </h2>
        <!-- <p class="lead">
            by <a href="index.php">Start Bootstrap</a>
        </p> -->
        <p><i class="fa fa-clock-o"></i> Сентябрь 2, 2015, 23:00</p>
        <hr>
        
        <p>
          Мы хотим сформировать сообщество в интернете, в котором люди изучают математику, решая и проверяя друг у друга задачи. Для этого мы создали этот вебсайт, и сегодня приглашаем всех учиться к нам. Вдохновила нас на это система математического образования Н.Н.Константинова, которая эффективно работает на кружках, в матшколах, и на математических факультетах. Мы создаем возможность изучать математику по этой методике в интернете (читать подробнее о методике <a href="http://www.evarist.org/about">у нас на сайте</a> ), основываясь на опыте форумов <a href="http://mathoverflow.net/">mathoverflow</a> и <a href="http://math.stackexchange.com/">mathstackexchange</a>.
        </p>
        <p>
          Мы начинаем с курса <a href="http://www.evarist.org/course/matan">математического анализа</a> 57-ой школы, по которому обучались сами. Так же этой осенью на нашем сайте будут сдаваться задачи и выкладываться лекции по трем курсам университетского уровня. Это <a href="http://www.evarist.org/course/cosmology">курс по космологии</a> на физфаке, курс о действиях тора из НМУ и курс по оптимальным методам управления на мехмате. Проходить их приглашаются все желающие, в том числе те, кто не посещает курсы вживую.
        </p>
        <p>
          Работает все довольно просто. Вы заходите в интересующую вас тему, предположим в <a href="http://www.evarist.org/problem_sets/teoriya-graphov-1/">теорию графов</a>. Решаете какую-нибудь задачу, например, восьмую и нажимаете на <a href="http://www.evarist.org/problem_sets/teoriya-graphov-1/problem/55ba153d3eab101ba023bf22/">отправить решение</a>. На появившейся страничке вы, предварительно <a href="http://www.evarist.org/user/login">зарегистрировавшись или зайдя через google</a>, записываете свое решение. Далее те, кто уже решил эту задачу, проверяют ваше решение. Действует простое правило: решения задачи, написанные остальными учащимися, становятся видны, только если ваше решение правильное. Если решение оказалось неверным, то вы исправляете его в соответствии с замечаниями, оставленными проверяющим. 
        </p>
         <p>  
          Еще одна деталь. На сайте у каждого пользователя есть "карма" - число, которое отражает уровень активности. Чем больше вы решаете и (особенно) проверяете, тем больше у вас карма.
        </p> 
        <p> 
          Всем добро пожаловать, и удачи с задачами!
        </p> 
        <p>
          Леша и Артем.
        </p>
        <p>
          P.S. Если вы хотите помочь запустить наше сообщество, то заходите <a href="https://github.com/artofkot/evarist">сюда</a>; вопросы и идеи пишите <a href="http://www.evarist.org/contact">здесь</a>.
        </p>

        <hr>
      </div>
    </div>
  </div>


{% endblock %}

evarist/templates/contact.html
{% extends "layout.html" %}
{% block head %}
   <title>Контакты</title>
{% endblock %}

{% block body %}

  
  <div style='height:20px'></div>

  <div class="row"> 
    <div class="col-md-6 col-md-offset-2">
      <p>
        <ol class="list-unstyled"> 
          Авторы проекта:
          <li>
            Алексей Левин,
            <em>alexej.levin@gmail.com</em>
          </li>
          <li>
            Артем Котельский,
            <em>artemk@math.princeton.edu</em>
          </li>
        </ol>
      </p>

      <hr>
      {% if g.user %}
        <p><b>Вопросы и пожелания пишите сюда, будем очень рады.</b></p>

        <form action="{{url_for('workflow.contact')}}" method="post">
          <div class="form-group" >
            {{ website_feedback_form.hidden_tag() }}

            <textarea class="form-control" rows="5"  name='feedback'></textarea>
            
            {% if not g.user%}
              {{website_feedback_form.email.label('Ваш e-mail')}}
              {{website_feedback_form.email(class='form-control')}}
            {%endif%}

          </div>
          <button type="submit" class="btn btn-default">Отправить</button>
        </form>
      {% else %}
        <p>
          <a href="{{url_for('user.login')}}">Войдите</a> на сайт чтобы послать нам сообщение.
        </p>
      {% endif %}
    </div>
  </div>
{% endblock %}

evarist/templates/course.html
{% extends "layout.html" %}
{% block head %}
   <title>{{course['name']}}</title>
{% endblock %}
{% block body %}

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <a href="{{url_for('workflow.home')}}">К главной странице</a>
    </div>
  </div>

  <!-- <div style='height:20px'></div> -->

  <hr>

  <div class="row">
    <div class="col-md-5 col-md-offset-2 problem_set">
      <div class="panel panel-default" id='matan-course-panel'>
        <div class="panel-heading">
          <h3>{{course.name}}</h3>
        </div>

        <div class="panel-body">
            <ol style='list-style-type:none'>
              {%for problem_set in course.problem_sets%}
                <li>
                  <p><a href="{{url_for('.problem_set',problem_set_slug=problem_set['slug'])}}">{{problem_set['title']}}</a></p>
                </li>
              {% endfor %}
            </ol>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

evarist/templates/entry.html
{% import 'macros/entries.html' as entry_macros %}

{% extends "layout.html" %}
{% block head %}
   <title></title>
{% endblock %}
{% block body %}

  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      {{entry_macros.entry(entry, entry_type=entry.get('entry_type'))}}
    </div>
  </div>

{% endblock %}

evarist/templates/layout.html
<!doctype html>
<!-- <html lang="en">  // ?? -->
<html>

  <head>
    <meta charset="utf-8"> <!-- as early as possible -->
    
    <!-- <title>Evarist</title> -->
      
    <!-- Google analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-56745698-2', 'auto');
      ga('send', 'pageview');
    </script>

    <!-- Yandex.Metrika counter --><script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter31555213 = new Ya.Metrika({ id:31555213, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/31555213" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
    <!-- I added it early, so that even if user closes window, metrika catches him -->

    <!-- Bootstrap headers from official Get Started -->
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1"> 
      <!-- maximum-scale=1, user-scalable=no --> <!-- add if u want it to look like a native app-->

      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

      <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"> -->
      <link rel="stylesheet" href="/static/vendor/bootstrap-3.3.2-dist/css/bootstrap.min.css">
      <!-- <link rel="stylesheet" href="/static/vendor/bootstrap-3.3.2-dist/css/bootstrap-theme.min.css"> -->
      <!-- <link rel="stylesheet" href="/static/bootstrap_paper_custom.min.css">  -->

      <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/css/bootstrap.min.css"> --> <!-- just use the latest -->

      <!-- todo: fallback: http://eddmann.com/posts/providing-local-js-and-css-resources-for-cdn-fallbacks/ -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
      <!-- <script src="/static/vendor/bootstrap-3.3.2-dist/js/bootstrap.min.js"></script>--> 


      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->

    <!-- mathjax -->
      <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
          tex2jax: {
            inlineMath: [['$','$'], ['\\(','\\)']],
            processEscapes: true,
            skipTags: ["script","noscript","style","textarea","code"]
          }
        });
      </script>
      <script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>

    <!-- Fonts -->
    <link href="https://cdn.rawgit.com/Aelay/aelay.github.io/master/ComputerModern/Bright/cmun-bright.css" rel="stylesheet" type="text/css">
    
    <link href="/static/style.css" rel="stylesheet" type="text/css">
    <script type='text/javascript' src='/static/js/scripts.js'></script>
    

    {% block head %}{% endblock %}
  </head>


  <body> 
    <div class=page>
      <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container" >
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{{ url_for('workflow.home')}}"> Evarist<sub style='color:green'>&#945</sub> </a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Полезные ссылки<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li>
                      <a href="http://www.evarist.org/blog#first_blogpost">Блогпост о запуске проекта</a> 
                    </li>
                    <li>
                      <a href="http://www.evarist.org/problem_sets/solution_examples/">
                      Примеры правильных решений
                      </a> 
                    </li>
                    <li>
                      <a href="{{url_for('workflow.users')}}">Топ 10 пользователей</a> 
                    </li>
                  

                    {% if g.user%}
                    <li>
                      <a href="{{url_for('workflow.my_solutions')}}">Мои решения</a> 
                    </li>
                    <li>
                      <a href="{{url_for('workflow.check')}}">Cмотреть и проверять чужие решения</a> 
                    </li>
                    {% else %}
                    <li>
                      <a href="{{url_for('user.login')}}">Зарегистрироваться</a> 
                    </li>
                    {%endif%}
                  </ul>
                </li>
                <!-- <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">О нас <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{{ url_for('workflow.faq')}}" in_tag="ul" kaspersky_status="skipped"> FAQ </a></li>
                    <li><a href="{{ url_for('workflow.about')}}" in_tag="ul" kaspersky_status="skipped"> О проекте </a></li>
                    <li><a href="{{ url_for('workflow.contact')}}"> Контакты </a></li>
                  </ul>
                </li> -->

                <li><a href="{{ url_for('workflow.faq')}}" in_tag="ul" kaspersky_status="skipped"> FAQ </a></li>
                <li><a href="{{ url_for('workflow.about')}}" in_tag="ul" kaspersky_status="skipped"> О проекте </a></li>
                <li><a href="{{ url_for('workflow.contact')}}"> Контакты </a></li>
              </ul>




              <ul class="nav navbar-nav navbar-right">
                <!-- <li>
                  {% if session['lang']=='en'%}
                  <a href="{{ url_for('workflow.lang_ru') }}?pa={{request.url}}"><small>view RU</small></a>
                  {%else%}
                  <a href="{{ url_for('workflow.lang_en') }}?pa={{request.url}}"><small>view EN</small></a>
                  {%endif%}
                </li> -->

                {% if not g.user%}
                  <li>
                    <form class="navbar-form" class="metanav" action="{{ url_for('user.login') }}" method=post>
                      <a href="{{ url_for('user.login') }}" class="btn btn-default" role="button">Login</a>
                    </form>
                  </li>

                {% else %}
                  <li>
                    {% if g.user.gplus_picture %}
                    <div>
                      <img src="{{g.user.gplus_picture}}" style='height:50px;width=50px;border-radius: 150px;-webkit-border-radius: 150px;-moz-border-radius: 150px; vertical-align:middle '>
                    </div>
                    {% endif %}
                  </li>
                  <li> <a href="{{ url_for('workflow.home') }}">{{g.user | safe}} </a></li>
                  <li><a href="{{ url_for('user.logout') }}">Log out</a></li>
                {% endif%}

                {% if g.user and g.user.rights.is_moderator%}
                  <li><a href="{{url_for('admin.home')}}">[admin interface]</a></li>
                {%endif%}
              </ul>

            </div>
          </div>
        </nav>

        {% for message in get_flashed_messages() %}
          <div class='row'>
            <div class="col-md-8 col-md-offset-2">
              <div class="flash">
                <h3 style="color:green">{{ message }}</h3>
              </div>
            </div>
          </div>          
        {% endfor %}
      </div>
      <div class="container">
        {% block body %}{% endblock %}
      </div>

      <!-- chat widget -->
      <script type="text/javascript">
        // var chatovodOnLoad = chatovodOnLoad || [];
        // chatovodOnLoad.push(function() {
        //     chatovod.addChatButton({host: "evarist.chatovod.com", align: "bottomRight",
        //         width: 600, height: 380, defaultLanguage: "en"});
        // });
        // (function() {
        //     var po = document.createElement('script');
        //     po.type = 'text/javascript'; po.charset = "UTF-8"; po.async = true;
        //     po.src = (document.location.protocol=='https:'?'https:':'http:') + '//st1.chatovod.com/api/js/v1.js?2';
        //     var s = document.getElementsByTagName('script')[0];
        //     s.parentNode.insertBefore(po, s);
        // })();
      </script>

      <div class="container" style="backgroud-color:#f5f5f5">
        <footer class="footer">
          <div class="container">
            <p class="text-muted">  </p>
          </div>
        </footer>
      </div>
    </div>
  </body>
</html>

evarist/templates/problem_set.html
{% extends "layout.html" %}
{% block head %}
   <title>{{problem_set['title']}}</title>
{% endblock %}
{% block body %}
  
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      {% if problem_set.course%}
        <a href="{{url_for('workflow.course', course_slug=problem_set.course.slug)}}">К странице курса</a>
      {% else %}
        <a href="{{url_for('workflow.home')}}">К главной странице</a>
      {% endif %}
    </div>
  </div>

  <!-- <div style='height:20px'></div> -->

  <hr>


  <div class="row">
    <div class="col-md-8 col-md-offset-2 problem_set">
      <h2 class="text-center"> {{problem_set['title']}}</h2>
      {%for content_block in problem_set['content_blocks']%}
        <div>
          <p>
          {% if content_block.type_=='problem' %}
            {% if engtag=='eng' %}
                <a class="def_prob_as_link" href="{{ url_for('workflow.problem', problem_set_slug=problem_set['slug'], prob_id=content_block.id ) }}">
                Problem {{content_block.number_in_problem_set}}.</a>
            {% else %}
                <a class="def_prob_as_link" href="{{ url_for('workflow.problem', problem_set_slug=problem_set['slug'], prob_id=content_block.id ) }}">
                Задача {{content_block.number_in_problem_set}}.</a>
            {%endif%}
          {% elif content_block.type_=='definition' %}
              {% if engtag=='eng' %}
                <a class="def_prob_as_link" href="{{ url_for('workflow.content_block', problem_set_slug=problem_set['slug'], type_=content_block.type_, __id=content_block.id ) }}">
                ∆ Definition {{content_block.number_in_problem_set}}.</a></a>
              {% else %}
                <a class="def_prob_as_link" href="{{ url_for('workflow.content_block', problem_set_slug=problem_set['slug'], type_=content_block.type_, __id=content_block.id ) }}">
                ∆ Определение {{content_block.number_in_problem_set}}.</a></a> 
              {%endif%}
            {%endif%}
          <span class="content_block">{{content_block['text']|safe}}</span>
          
          {% if content_block.type_=='problem' %}
            <a class="btn btn-s btn-default pull-right" href="{{ url_for('workflow.problem', problem_set_slug=problem_set['slug'], prob_id=content_block.id ) }}" >
            
            {% if engtag=='eng' %}
                Send a solution
            {% else %}
                Отправить решение
            {%endif%}
            </a>
          {%endif%}
          </p>
          <br>
        </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

evarist/templates/upload_form.html
{% extends "layout.html" %}
{% block head %}
  <title></title>
  <script src="/js/jquery-2.0.1.min.js"></script>
  <link rel="stylesheet" href="/js/redactor/redactor.css" />
  <script src="/js/redactor/redactor.js"></script>
  
  <script type="text/javascript">
  $(function()
  {
  $('#content').redactor();
  });
  </script>


{% endblock %}
{% block body %}


<h1>Upload new Image</h1>
<form action="" method="post" enctype="multipart/form-data">
  <p>
  <input type="file" name="file">
  <input type="submit" value="Upload">
  </p>
</form>
{% if upload_result %}
  <h3>Upload API Result</h3>
  <div>{{ upload_result }}</div>
  <h3>Thumbnails:</h3>
  <div><a href="{{thumbnail_url1}}">{{thumbnail_url1}}</a></div>
  <img src="{{ thumbnail_url1 }}"/>
  <div><a href="{{thumbnail_url2}}">{{thumbnail_url2}}</a></div>
  <img src="{{ thumbnail_url2 }}"/>
  <h3>Original:</h3>
  <img src="{{ upload_result['url'] }}"/>
{% endif %}



  <textarea id="content" name="content"></textarea>


{%endblock%}